AllCops:
  TargetRubyVersion: 2.5
  RubyInterpreters:
    - ruby
  Exclude:
    - '**/*.gemspec'
    - 'test/**/*.rb'
    - 'examples/**/*.rb'
    - 'Gemfile*'
    - lib/polyphony/http/agent.rb

Style/LambdaCall:
  Enabled: false
# Style/ModuleFunction:
#   Enabled: false
# Style/RegexpLiteral:
#   Enabled: false

# Naming/MemoizedInstanceVariableName:
#   Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/SpecialGlobalVars:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/InheritException:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - lib/polyphony/auto_run.rb
    - lib/polyphony/extensions/core.rb
    - examples/**/*.rb

Style/ClassVars:
  Exclude:
    - lib/polyphony/core/coprocess.rb

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Naming/AccessorMethodName:
  Exclude:
    - lib/polyphony/http/server/http1.rb
    - lib/polyphony/http/server/http2_stream.rb
    - examples/**/*.rb

Naming/MethodName:
  Exclude:
    - test/test_signal.rb

Lint/HandleExceptions:
  Exclude:
    - lib/polyphony/http/server/http1.rb
    - lib/polyphony/http/server/http2.rb
    - lib/polyphony/http/server/http2_stream.rb
    - lib/polyphony/http/server.rb
    - examples/**/*.rb

Metrics/MethodLength:
  Exclude:
    - lib/polyphony/http/server/rack.rb
    - lib/polyphony/extensions/io.rb
    - test/**/*.rb
    - examples/**/*.rb

Metrics/ModuleLength:
  Exclude:
    - lib/polyphony/extensions/core.rb
    - examples/**/*.rb

Metrics/ClassLength:
  Exclude:
    - lib/polyphony/http/server/http1.rb
    - test/**/*.rb
    - examples/**/*.rb

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - lib/polyphony/auto_run.rb
    - test/**/*.rb
    - examples/**/*.rb

Style/Documentation:
  Exclude:
    - test/**/*.rb
    - examples/**/*.rb

Style/FormatString:
  Exclude:
    - test/**/*.rb
    - examples/**/*.rb

Style/FormatStringToken:
  Exclude:
    - test/**/*.rb
    - examples/**/*.rb

Naming/UncommunicativeMethodParamName:
  Exclude:
    - test/**/*.rb
    - examples/**/*.rb

Security/MarshalLoad:
  Exclude:
    - examples/**/*.rb