title: "Polyphony"

remote_theme: pmarsceill/just-the-docs
color_scheme: dark

search_enabled: true
# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

plugins:
  - jekyll-remote-theme

aux_links:
  "Polyphony on GitHub":
    - "//github.com/digital-fabric/polyphony"