name: Tests (io_uring backend)

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [2.6, 2.7]

    name: >-
      ${{matrix.os}}, ${{matrix.ruby}}

    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - name: Upgrade kernel
      run: sudo bin/upgrade-kernel.sh
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Compile C-extension
      run: bundle exec rake compile
    - name: Run tests
      run:  bundle exec rake test
